//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Biblioteca.Models.EntidadesBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int idPrestamo { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<int> idTipoPrestamo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual TipoPrestamo TipoPrestamo { get; set; }
    }
}
