//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Biblioteca.Models.EntidadesBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int idRespuesta { get; set; }
        public Nullable<int> idPregunta { get; set; }
        public string respuesta1 { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<System.DateTime> fechaRespuesta { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
