//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Biblioteca.Models.EntidadesBiblioteca
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administradors { get; set; }
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<Pregunta> Preguntas { get; set; }
        public virtual DbSet<Prestamo> Prestamoes { get; set; }
        public virtual DbSet<Respuesta> Respuestas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoPrestamo> TipoPrestamoes { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<string> SP_login_administrador(string correo, string contrasena)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_login_administrador", correoParameter, contrasenaParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_S_Preguntas_Result> SP_S_Preguntas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_S_Preguntas_Result>("SP_S_Preguntas");
        }
    
        public virtual int SP_I_pregunta(string titulo, string tipoDeDato, string respuestas, Nullable<int> creadaPor)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var tipoDeDatoParameter = tipoDeDato != null ?
                new ObjectParameter("tipoDeDato", tipoDeDato) :
                new ObjectParameter("tipoDeDato", typeof(string));
    
            var respuestasParameter = respuestas != null ?
                new ObjectParameter("respuestas", respuestas) :
                new ObjectParameter("respuestas", typeof(string));
    
            var creadaPorParameter = creadaPor.HasValue ?
                new ObjectParameter("creadaPor", creadaPor) :
                new ObjectParameter("creadaPor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_I_pregunta", tituloParameter, tipoDeDatoParameter, respuestasParameter, creadaPorParameter);
        }
    
        public virtual int SP_D_borrarPregunta(Nullable<int> idPregunta)
        {
            var idPreguntaParameter = idPregunta.HasValue ?
                new ObjectParameter("idPregunta", idPregunta) :
                new ObjectParameter("idPregunta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_D_borrarPregunta", idPreguntaParameter);
        }
    
        public virtual int SP_D_tipoPrestamo(Nullable<int> idTipoPrestamo)
        {
            var idTipoPrestamoParameter = idTipoPrestamo.HasValue ?
                new ObjectParameter("idTipoPrestamo", idTipoPrestamo) :
                new ObjectParameter("idTipoPrestamo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_D_tipoPrestamo", idTipoPrestamoParameter);
        }
    
        public virtual int SP_I_tipoPrestamo(string nombrePrestamo, string descripcion)
        {
            var nombrePrestamoParameter = nombrePrestamo != null ?
                new ObjectParameter("nombrePrestamo", nombrePrestamo) :
                new ObjectParameter("nombrePrestamo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_I_tipoPrestamo", nombrePrestamoParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<SP_S_tipoPrestamo_Result> SP_S_tipoPrestamo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_S_tipoPrestamo_Result>("SP_S_tipoPrestamo");
        }
    
        public virtual int SP_I_Prestamo(Nullable<int> idAlumno, Nullable<int> idTipoPrestamo)
        {
            var idAlumnoParameter = idAlumno.HasValue ?
                new ObjectParameter("idAlumno", idAlumno) :
                new ObjectParameter("idAlumno", typeof(int));
    
            var idTipoPrestamoParameter = idTipoPrestamo.HasValue ?
                new ObjectParameter("idTipoPrestamo", idTipoPrestamo) :
                new ObjectParameter("idTipoPrestamo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_I_Prestamo", idAlumnoParameter, idTipoPrestamoParameter);
        }
    
        public virtual int SP_I_alumno(Nullable<int> matricula)
        {
            var matriculaParameter = matricula.HasValue ?
                new ObjectParameter("matricula", matricula) :
                new ObjectParameter("matricula", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_I_alumno", matriculaParameter);
        }
    
        public virtual ObjectResult<SP_S_preguntasFaltantes_Result> SP_S_preguntasFaltantes(Nullable<int> idAlumno)
        {
            var idAlumnoParameter = idAlumno.HasValue ?
                new ObjectParameter("idAlumno", idAlumno) :
                new ObjectParameter("idAlumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_S_preguntasFaltantes_Result>("SP_S_preguntasFaltantes", idAlumnoParameter);
        }
    
        public virtual int SP_U_completoCuestionario(Nullable<int> idAlumno)
        {
            var idAlumnoParameter = idAlumno.HasValue ?
                new ObjectParameter("idAlumno", idAlumno) :
                new ObjectParameter("idAlumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_U_completoCuestionario", idAlumnoParameter);
        }
    
        public virtual int SP_U_desacompletarCuestionario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_U_desacompletarCuestionario");
        }
    
        public virtual int SP_I_respuesta(Nullable<int> idPregunta, string respuesta, Nullable<int> idAlumno)
        {
            var idPreguntaParameter = idPregunta.HasValue ?
                new ObjectParameter("idPregunta", idPregunta) :
                new ObjectParameter("idPregunta", typeof(int));
    
            var respuestaParameter = respuesta != null ?
                new ObjectParameter("respuesta", respuesta) :
                new ObjectParameter("respuesta", typeof(string));
    
            var idAlumnoParameter = idAlumno.HasValue ?
                new ObjectParameter("idAlumno", idAlumno) :
                new ObjectParameter("idAlumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_I_respuesta", idPreguntaParameter, respuestaParameter, idAlumnoParameter);
        }
    }
}
