//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Biblioteca.Models.EntidadesBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregunta()
        {
            this.Respuestas1 = new HashSet<Respuesta>();
        }
    
        public int idPregunta { get; set; }
        public string titulo { get; set; }
        public string tipoDeDato { get; set; }
        public string respuestas { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> creadaPor { get; set; }
        public Nullable<bool> visible { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuestas1 { get; set; }
    }
}
